import { Link } from "wouter";
import { ArrowRight, ClipboardList, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { new: "New", in_review: "In review", assigned: "Assigned", awaiting_response: "Awaiting response", resolved: "Resolved", closed: "Closed" };
const colors: Record<string, string> = { new: "bg-[#edf3f0] text-[#53645b]", in_review: "bg-[#fff3d8] text-[#805f17]", assigned: "bg-[#e4efff] text-[#315d91]", awaiting_response: "bg-[#f4e8ff] text-[#70469b]", resolved: "bg-[#e5f5eb] text-[#217143]", closed: "bg-[#e8eceb] text-[#5e6d65]" };
export default function MyComplaints() {
  const { data, isLoading, error } = trpc.complaints.mine.useQuery();
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#0d5c48]">Your activity</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#193b2f]">My complaints</h1><p className="mt-2 text-[#65736c]">Follow the status of every complaint you have submitted.</p></div><Button asChild><Link href="/submit"><Plus size={16} /> New complaint</Link></Button></div>{isLoading ? <div className="mt-8 rounded-2xl border border-[#d9e3dd] bg-white p-8 text-sm text-[#65736c]">Loading your complaints…</div> : error ? <div className="mt-8 rounded-2xl border border-[#edc8c1] bg-[#fff4f1] p-5 text-sm text-[#8a3c2e]">We could not load your complaints. Please refresh and try again.</div> : !data?.length ? <div className="mt-8 rounded-2xl border border-dashed border-[#b9d5c8] bg-white p-12 text-center"><ClipboardList className="mx-auto text-[#0d5c48]" size={30} /><h2 className="mt-4 font-semibold text-[#193b2f]">No complaints yet</h2><p className="mt-2 text-sm text-[#65736c]">When you submit a complaint, its reference and current status will appear here.</p><Button asChild className="mt-5"><Link href="/submit">Submit your first complaint</Link></Button></div> : <div className="mt-8 grid gap-4">{data.map(item => <Link key={item.id} href={`/complaints/${item.id}`} className="block rounded-2xl border border-[#d9e3dd] bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-semibold tracking-wide text-[#0d5c48]">{item.reference}</div><h2 className="mt-2 font-semibold text-[#193b2f]">{item.subject}</h2></div><Badge className={colors[item.status] || colors.new}>{labels[item.status] || item.status}</Badge></div><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-[#718078]"><span>{item.category.replaceAll("_", " ")}</span><span>Priority: {item.priority}</span><span>Submitted {new Date(item.createdAt).toLocaleDateString()}</span>{item.assigneeName && <span>Assigned to {item.assigneeName}</span>}<ArrowRight size={15} className="ml-auto text-[#0d5c48]" /></div></Link>)}</div>}</div>;
}
